version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  core:
    build:
      context: ./core
      dockerfile: Dockerfile.dev
    container_name: core-worker
    volumes:
      - ./core:/app
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api-service
    volumes:
      - ./api:/app
    depends_on:
      - core
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    restart: always