version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - LANG=en_US.utf8

  postgres:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_USER: hls
      POSTGRES_PASSWORD: nmkj
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_service
    ports:
      - "6379:6379"

    core:
      build: ./core
      container_name: core-worker
      depends_on:
        - redis
      environment:
        - REDIS_ADDR=redis:6379
      restart: always

volumes:
  postgres_data:
