version: '3.8'
services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'video_minio_data:/data'
    environment:
       MINIO_ROOT_USER: minio
       MINIO_ROOT_PASSWORD: minio123 
    command: server --console-address ":9001" /data
volumes:
  video_minio_data:
